version: "3"
services:
  mindoc:
    image: registry.cn-qingdao.aliyuncs.com/dy-base/mindoc:1.0
    container_name: mindoc
    privileged: false
    restart: always
    ports:
      - 8181:8181
    volumes:
      - ./conf:/mindoc/conf
      - ./static:/mindoc/static
      - ./views:/mindoc/views
      - ./uploads:/mindoc/uploads
      - ./runtime:/mindoc/runtime
      # - ./database:/mindoc/database
    environment:
      # 基本配置
      - MINDOC_RUN_MODE=prod
      - MINDOC_BASE_URL=
      - MINDOC_CDN_IMG_URL=
      - MINDOC_CDN_CSS_URL=
      - MINDOC_CDN_JS_URL=
      - MINDOC_ENABLE_EXPORT=false
      # cache
      - MINDOC_CACHE=true
      - MINDOC_CACHE_PROVIDER=file
      # - MINDOC_CACHE_PROVIDER=redis
      # - MINDOC_CACHE_REDIS_HOST=xxxx:xxxx
      # - MINDOC_CACHE_REDIS_DB=0
      # - MINDOC_CACHE_REDIS_PASSWORD=xxxx
      # db
      - MINDOC_DB_ADAPTER=sqlite3
      - MINDOC_DB_DATABASE=./database/mindoc.db
      # - MINDOC_DB_ADAPTER=MySQL
      # - MINDOC_DB_HOST=127.0.0.1
      # - MINDOC_DB_PORT=3306
      # - MINDOC_DB_DATABASE=mindoc
      # - MINDOC_DB_USERNAME=mindoc
      # - MINDOC_DB_PASSWORD=123456
      # ldap
      # - MINDOC_LDAP_ENABLE=true
      # - MINDOC_LDAP_SCHEME=ldap
      # - MINDOC_LDAP_HOST=127.0.0.1
      # - MINDOC_LDAP_PORT=389
      # - MINDOC_LDAP_ACCOUNT=cn
      # - MINDOC_LDAP_MAIL=mail
      # - MINDOC_LDAP_BASE=ou=users,dc=xxxx,dc=xxx
      # - MINDOC_LDAP_USER=cn=admin,dc=xxx,dc=xxx
      # - MINDOC_LDAP_PASSWORD=xxxxxx
      # # ldap搜索filter规则
      # - MINDOC_LDAP_FILTER=objectClass=inetOrgPerson